# Generated by Django 5.2 on 2025-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='equipment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workout',
            name='rest',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=0),
        ),
    ]
