# Generated by Django 5.0 on 2025-04-22 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkout', '0002_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
