# Generated by Django 5.2 on 2025-04-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiworkout', '0002_workout_equipment_workout_rest_workout_sets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='badges/')),
                ('rule_type', models.CharField(max_length=100)),
                ('threshold', models.PositiveIntegerField()),
            ],
        ),
    ]
